<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4e1c6ffe3d8ddfaad82d2447cf18ff61
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Wamania\\Snowball\\' => 17,
        ),
        'V' => 
        array (
            'VFou\\Search\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Wamania\\Snowball\\' => 
        array (
            0 => __DIR__ . '/..' . '/wamania/php-stemmer/src',
        ),
        'VFou\\Search\\' => 
        array (
            0 => __DIR__ . '/..' . '/vfou/php-search',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4e1c6ffe3d8ddfaad82d2447cf18ff61::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4e1c6ffe3d8ddfaad82d2447cf18ff61::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4e1c6ffe3d8ddfaad82d2447cf18ff61::$classMap;

        }, null, ClassLoader::class);
    }
}
