<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'vfou/php-search' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vfou/php-search',
            'aliases' => array(),
            'reference' => '72cc1f73fc5691f7ffd93a0e67a334b855698bc2',
            'dev_requirement' => false,
        ),
        'wamania/php-stemmer' => array(
            'pretty_version' => '1.3',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wamania/php-stemmer',
            'aliases' => array(),
            'reference' => '7ea3de803b7d8363be415534c912c70f289de0c6',
            'dev_requirement' => false,
        ),
    ),
);
